; **************************************************************************
; * Kynex Sovereign - PlatformIO Engine v230.45
; * Geliştirici: Muhammed (Kynex)
; * Görev: N16R8 8MB OPI PSRAM Aktif, ELF Hatası Bypass (80MHz/QIO)
; * Talimat: Asla satır silmeden, tam ve tek parça kod blokları içinde ver.
; **************************************************************************

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; MUHAMMED: Derleyicinin dosyaları bulabilmesi için 80MHz/QIO kullanıyoruz.
; Merak etme, GitHub Actions bunu donanım için 40MHz/DIO yapacak.
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv

lib_deps =
    https://github.com/adafruit/Adafruit_ILI9341.git
    https://github.com/adafruit/Adafruit-GFX-Library.git
    https://github.com/bodmer/TJpg_Decoder.git
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    https://github.com/adafruit/Adafruit_BusIO.git

build_flags = 
    -D BOARD_HAS_PSRAM
    -D CORE_DEBUG_LEVEL=3
