; **************************************************************************
; * KynexOs v156.0 - PlatformIO Cloud Config (Partition Fix)
; * Geliştirici: Muhammed (Kynex)
; * Donanım: ESP32-S3 N16R8 (DIO+OPI)
; * Talimat: Asla satır silme, optimize etme, sadeleştirme yapma.
; **************************************************************************

[env:esp32-s3-devkitc-1]
platform = espressif32 @ 6.5.0
board = esp32-s3-devkitc-1
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_upload.flash_size = 16MB
board_build.psram = enabled
board_build.arduino.memory_type = dio_opi

; MUHAMMED: İŞTE HATA BURADAYDI! default_16MB.csv yerine BİZİM haritamız (partitions.csv) kullanılmalı!
board_build.partitions = partitions.csv

; MUHAMMED: İŞTE O SİHİRLİ SATIR. Resim doğrudan gömülüyor.
board_build.embed_files = src/wallpaper.jpg

lib_deps = 
    Adafruit ILI9341
    Adafruit GFX Library
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    TJpg_Decoder
    WiFi
    WebServer
    FS
    FFat
    Preferences

build_flags = 
    -D CORE_DEBUG_LEVEL=0
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D TFT_BL=1
    -D TFT_CS=10    
    -D TFT_DC=9     
    -D TFT_RST=14   
    -D TFT_MOSI=11  
    -D TFT_SCK=12   
    -D TOUCH_CS=16  
    -D MISO_PIN=13  
    -D JOY1_X=4
    -D JOY1_Y=5
    -D JOY1_SW=6
    -D JOY2_X=7
    -D JOY2_Y=15
    -D JOY2_SW=17
    -D SPEAKER_PIN=18

monitor_speed = 115200
upload_speed = 921600
