name: KynexOs Sovereign Build v123

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v4

      - name: PlatformIO Onbellegini Kuru
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio
          key: ${{ runner.os }}-platformio-permanent-v123

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: PlatformIO Yukle ve Derle
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio run

      - name: Bin Dosyasini Paylas
        uses: actions/upload-artifact@v4
        with:
          name: KynexOs_Firmware_Absolute
          path: .pio/build/esp32-s3-devkitc-1/firmware.bin
          compression-level: 0
